# Generated by Django 4.0.6 on 2022-07-29 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128)),
                ('slug', models.CharField(max_length=128)),
                ('courses_count', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('slug', models.CharField(max_length=128)),
                ('image', models.ImageField(max_length=128, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('slug', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to='course/')),
                ('level', models.CharField(choices=[('1', 'beginner'), ('2', 'intermediate'), ('3', 'advanced')], max_length=128)),
                ('type', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], max_length=128)),
                ('duration', models.CharField(choices=[('0-1', '0-1 Hour'), ('1-3', '1-3 Hour'), ('3+', '3+ Hour')], max_length=128)),
                ('students_count', models.PositiveIntegerField()),
                ('rating', models.FloatField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='courses', to='course.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='courses', to='course.category')),
                ('tags', models.ManyToManyField(related_name='courses', to='course.tag')),
            ],
        ),
    ]
